language: go
go:
- tip
notifications:
  email: false
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- go get -t -v ./...
script:
- export GODEBUG=http2debug=2
- go test -v -race -covermode=atomic -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN
env:
- GODEBUG=http2debug=2
- secure: gRfV5W/KGO4JQ1lVHpgfwTuk712MCK9Nwahp1WC2TrRJxsgSkdCOO6P3XCfiSQ10vnnOuRlJZ+0xkJ/la9Rf0kmW8x5nYDCwwF83XN9pC9a8FR2XvZn1uiQjxbQI0zsGEIFW+a6OgNQ7PXD/3iO9PVGOnTHNuW8cx8quMj78m4n+qw3po65V/RihG6zmpU7N6BGKXOjzh9F/YTZNqvwRKQFKsvSQAd9+53iagy1+lD6wqLaMQ2Rh35nQxREAFFHX9dDxLanfi/iLJTXbaZ9eozQkIQJudGkbQ0S0XLHwLiBf4/LE7lLxhcwzKs+HluAv1nKYr9MbI+yP5Csctp9lQQl2LLfVmu1ZLSHN8Y4q+/UO7fAFbYWrNcwoI9oeZumv0QnTB7M76MTZRA5RRL6/7J5mEdRzt5ssMYnryN97tImzhfBk0OUWrUIJyoeptsKwrYjJF2EVIH1gxgerUX6B6rGPXd29MVju5VlLPCtMnFV06ZTc6FMqX2F/u5NIG+EAaELuV8HpJlDIb0FPozSl+5xDsoyx741Do2+m23RVd42Yi/GeUUXiIVeFIyGR6iX/eFJaikn7Gqqmuo/20XK3k2lGIB4un4l6gDcviC5niL25HGf2IHbhK3767j/Vx4cwuE495NXcb4ufU8SEtzt7iNko4pERddSywCw4zMJvlsE=
